In [1]:
import os
import numpy as np
import pandas as pd
import json
import cv2

import tensorflow as tf
from tensorflow import keras
import tensorflow_hub as hub

from keras import layers, models, optimizers, regularizers
from keras.applications import EfficientNetB0
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# import matplotlib.pyplot as plt

In [2]:
# test if running the GPU version of tensorflow
tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [3]:
# loads directory of 3 datasets
dir_train = pd.read_csv('dataset/EuroSAT/train.csv')
dir_valid = pd.read_csv('dataset/EuroSAT/validation.csv')
dir_test = pd.read_csv('dataset/EuroSAT/test.csv')


In [6]:
# ## verify all 3 directories are equally sliced across 10 categories

# temp1 = dir_test['Label'].value_counts() / dir_test.shape[0]
# temp2 = dir_train['Label'].value_counts() / dir_train.shape[0]
# temp3 = dir_valid['Label'].value_counts() / dir_valid.shape[0]
# df_temp = pd.concat([temp1, temp2, temp3], axis=1)
# df_temp

# ## evenly sliced by category

In [4]:
img_dir = pd.concat([dir_train, dir_valid], ignore_index=False)
img_dir = img_dir.iloc[:,1:-1].reset_index().drop(['index'], axis=1)
print(img_dir.shape)
# img_dir = img_dir.iloc[:100, :] # limit sample size when testing
img_dir

(24300, 3)


Filename  Label  \
0                          AnnualCrop/AnnualCrop_142.jpg      0   
1      HerbaceousVegetation/HerbaceousVegetation_2835...      2   
2                   PermanentCrop/PermanentCrop_1073.jpg      6   
3                          Industrial/Industrial_453.jpg      4   
4      HerbaceousVegetation/HerbaceousVegetation_1810...      2   
...                                                  ...    ...   
24295                           SeaLake/SeaLake_1943.jpg      9   
24296                      AnnualCrop/AnnualCrop_211.jpg      0   
24297                     Industrial/Industrial_1428.jpg      4   
24298                     AnnualCrop/AnnualCrop_2571.jpg      0   
24299                               River/River_1418.jpg      8   

                  ClassName  
0                AnnualCrop  
1      HerbaceousVegetation  
2             PermanentCrop  
3                Industrial  
4      HerbaceousVegetation  
...                     ...  
24295               SeaLake  
24296            AnnualCrop  
24297            Industrial  
24298            AnnualCrop  
24299                 River  

[24300 rows x 3 columns]

In [5]:
# Load images and labels/classes
images = []
classes = []
# labels.typeof()

base_path = 'dataset/EuroSAT/'
for index, row in img_dir.iterrows():
    img_path = os.path.join(base_path, row['Filename'])
    img = cv2.imread(img_path)
    img = cv2.resize(img, (224, 224))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    images.append(img)
    classes.append(row['ClassName'])

# Normalize images
images = np.array(images) / 255.0
labels = pd.get_dummies(classes).values

In [6]:
images.shape

(24300, 224, 224, 3)

In [7]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

# Set up the data augmentation
train_data_generator = ImageDataGenerator(
    rotation_range=180,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    vertical_flip=True
)
valid_data_generator = ImageDataGenerator()

In [8]:
MODEL_PATH = "https://tfhub.dev/sayakpaul/convnext_base_21k_1k_224_fe/1"

# hub_layer = hub.KerasLayer(model_path, trainable=False)

def get_model(model_path=MODEL_PATH, res=224, num_classes=10):
    hub_layer = hub.KerasLayer(model_path, trainable=False)
    model = keras.Sequential(
        [
            keras.layers.InputLayer((res, res, 3)),
            hub_layer,
            # layers.Dense(512, activation="relu", kernel_regularizer=regularizers.l2(0.001)),
            # layers.BatchNormalization(),
            # layers.Dropout(0.5),
            layers.Dense(256, activation="relu", kernel_regularizer=regularizers.l2(0.001)),
            layers.BatchNormalization(),
            layers.Dropout(0.5),
            keras.layers.Dense(num_classes, activation="softmax"),
        ]
    )
    return model

model_1 = get_model()
model_1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer (KerasLayer)    (None, 1024)              87566464  
                                                                 
 dense (Dense)               (None, 256)               262400    
                                                                 
 batch_normalization (BatchN  (None, 256)              1024      
 ormalization)                                                   
                                                                 
 dropout (Dropout)           (None, 256)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                2570      
                                                                 
Total params: 87,832,458
Trainable params: 265,482
Non-trainable params: 87,566,976
______________________________________

In [14]:
# # Compile the model
# model_1.compile(optimizer=optimizers.Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# # Train the model
# batch_size = 32
# epochs = 5
# validation_steps = len(X_test) // batch_size

# history = model_1.fit(train_data_generator.flow(X_train, y_train, batch_size=batch_size), validation_data=valid_data_generator.flow(X_test, y_test, batch_size=batch_size), validation_steps=validation_steps, epochs=epochs)

Epoch 1/5
608/608 [==============================] - 881s 1s/step - loss: 0.8132 - accuracy: 0.8666 - val_loss: 0.6546 - val_accuracy: 0.9077
Epoch 2/5
608/608 [==============================] - 860s 1s/step - loss: 0.5642 - accuracy: 0.9164 - val_loss: 0.5445 - val_accuracy: 0.9178
Epoch 3/5
608/608 [==============================] - 856s 1s/step - loss: 0.4757 - accuracy: 0.9241 - val_loss: 0.4681 - val_accuracy: 0.9191
Epoch 4/5
608/608 [==============================] - 856s 1s/step - loss: 0.4222 - accuracy: 0.9257 - val_loss: 0.4230 - val_accuracy: 0.9243
Epoch 5/5
608/608 [==============================] - 855s 1s/step - loss: 0.3895 - accuracy: 0.9281 - val_loss: 0.4646 - val_accuracy: 0.9067


In [18]:
# model_1.save("model_1_nFull_epoch5_batch32")

INFO:tensorflow:Assets written to: model_1_nFull_epoch5_batch32\assets


INFO:tensorflow:Assets written to: model_1_nFull_epoch5_batch32\assets


In [9]:
## if want to load later on: 
from tensorflow.keras.models import load_model
model_1 = load_model("model_1_nFull_epoch5_batch32")

In [10]:
# Evaluate the model
batch_size = 32  # Choose a smaller batch size according to your GPU memory capacity
y_pred_batches = []

for i in range(0, len(X_test), batch_size):
    batch_pred = model_1.predict(X_test[i:i + batch_size])
    y_pred_batches.append(batch_pred)

y_pred = np.concatenate(y_pred_batches, axis=0)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# y_pred = model_1.predict(X_test)
# y_pred_classes = np.argmax(y_pred, axis=1)
# y_true = np.argmax(y_test, axis=1)

1/1 [==============================] - 3s 3s/step


In [11]:
print(classification_report(y_true, y_pred_classes))
print(confusion_matrix(y_true, y_pred_classes))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94       551
           1       0.79      0.99      0.88       547
           2       0.91      0.87      0.89       535
           3       0.93      0.93      0.93       459
           4       0.99      0.71      0.83       453
           5       0.97      0.86      0.91       371
           6       0.94      0.88      0.91       456
           7       0.82      0.87      0.84       502
           8       0.92      0.96      0.94       469
           9       0.99      0.98      0.98       517

    accuracy                           0.91      4860
   macro avg       0.92      0.90      0.91      4860
weighted avg       0.91      0.91      0.91      4860

[[533   4   0   0   0   2   5   0   5   2]
 [  2 544   0   0   0   0   0   0   0   1]
 [  0  54 467   0   0   4   5   0   4   1]
 [  5   3   2 426   2   2   3   4  11   1]
 [  1   0   1  19 322   0   8  93   9   0]
 [  6  32   3   1   0 320 

##### If you want to save the model: 

In [ ]:
# model_1.save("model_1")

# ## if want to load later on: 
# from tensorflow.keras.models import load_model
# loaded_model = load_model("model_1")

INFO:tensorflow:Assets written to: model_1\assets


INFO:tensorflow:Assets written to: model_1\assets


## Draft / Archive (Plz disregard)

In [ ]:
# import matplotlib.pyplot as plt # somehow this just doesnt work

In [ ]:
# testing/debugging
# print(classes[0])
# images[0].shape

AnnualCrop


(224, 224, 3)

In [ ]:
# ## Use this when running for 1st time
# MODEL_PATH = "https://tfhub.dev/sayakpaul/convnext_base_21k_1k_224_fe/1"
# model = hub.load(MODEL_PATH)
# # saved_model_path = 'model/'
# # tf.saved_model.save(model, saved_model_path)

# # ## Use this for subsequent runs when model already loaded locally
# # saved_model_path = 'model/'
# # model = tf.saved_model.load(saved_model_path)